services:
  - type: web
    name: globalsolution
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar -Dspring.profiles.active=prod target/*.jar
    envVars:
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SPRING_PROFILES_ACTIVE
        value: prod
