spring:
  application:
    name: globalsolution
  datasource:
    url: ${env.DATABASE_URL}
    username: ${env.DATABASE_USERNAME}
    password: ${env.DATABASE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  ai:
    openai:
      api-key: ${env.OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  rabbitmq:
    host: ${env.RABBITMQ_HOST}
    port: ${env.RABBITMQ_PORT}
    username: ${env.RABBITMQ_USERNAME}
    password: ${env.RABBITMQ_PASSWORD}
  messages:
    basename: messages
    encoding: UTF-8

server:
  port: ${env.PORT:8080}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
